
export const ADD_TRAIL = 'ADD_TRAIL';

export const PROVENCES_LOADING = 'PROVENCES_LOADING';
export const PROVENCES_FAILED = 'PROVENCES_FAILED';
export const ADD_PROVENCES = 'ADD_PROVENCES';

export const COUNTIES_LOADING = 'COUNTIES_LOADING';
export const COUNTIES_FAILED = 'COUNTIES_FAILED';
export const ADD_COUNTIES = 'ADD_COUNTIES';

export const TRAILS_LOADING = 'TRAILS_LOADING';
export const TRAILS_FAILED = 'TRAILS_FAILED';
export const ADD_TRAILS = 'ADD_TRAILS';

